int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int _print_sign(int n);
int _abs(int);
int _print_last_digit(int n);
void _jack_bauer(void);
void _times_table(void);
int _add(int, int);
void _print_to_98(int n);
void _print_times_table(int n);
